apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: rpi-exporter
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      {{- include "rpi-exporter.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
    - path: /metrics
      port: http